language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install coveralls
script:
    - coverage run --source=kakasi_utils setup.py test
after_success:
    - coveralls
